server:
  port: 9090
  error:
    include-message: always
spring:
  datasource:
    #url: jdbc:oracle:thin:@oracle_xe:1521/XEPDB1
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ${APP_USERNAME}
    password: ${APP_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: none # ou create-drop, create, validate, none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true






