spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: root
    password: roudane123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: none # ou create-drop, create, validate, none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
