pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                // Étape pour construire l'application avec Maven
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                // Étape pour exécuter les tests avec Maven
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Changer de répertoire vers le répertoire "devOps"
                dir('devOps/backend') {
                    // Lancer les conteneurs Docker avec docker-compose
                    sh 'docker-compose up -d'
                }
            }
        }
    }

        pre {
            // Actions préliminaires
                dir('devOps/backend') {
                    // Lancer les conteneurs Docker avec docker-compose
                    sh 'docker-compose down'
                }
            }
}
