pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                // Étape pour construire l'application avec Maven
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                // Étape pour exécuter les tests avec Maven
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Lancer les conteneurs Docker avec docker-compose
                sh 'cd devOps/backend'
                sh 'docker-compose up -d'
            }
        }
    }
}
