pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                // Étape pour construire l'application avec Maven
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                // Étape pour exécuter les tests avec Maven
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Étape pour déployer l'application
                sh 'java -jar target/couche-web-1.0-SNAPSHOT.jar'
            }
        }
    }
}
